[package]
name = "weather"
version = "0.1.0"
authors = ["Jim Rybarski <jim@rybarski.com>"]

[dependencies]
weathergov = "0.2.1"
thread_local = "1.1.4"
lock_api = "0.4.2"
hyper = "0.14.12"
tokio = "1.8.4"
